
# app1 service
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    type: ingress
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # volumes:
  #   - app_content/app1.html:/usr/share/nginx/html/index.html
---
# app1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: nginx:latest
          ports:
            - containerPort: 80
          