apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two-container
          image: paulbouwer/hello-kubernetes:1
          ports:
            - containerPort: 80
              protocol: TCP
          env:
          - name: MESSAGE
            value: "Hello from app2"
          - name: PORT
            value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  type: ClusterIP
  selector:
    app: app-two
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
