#!/bin/bash

# Reset DNS settings to default

# Check if running with root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Define default DNS servers
default_dns_servers=""

# Reset DNS settings to default
echo "Resetting DNS settings to default..."
echo "# Generated by resolvconf" > /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 8.8.4.4" >> /etc/resolv.conf

# these are the default one
echo "nameserver 127.0.0.53" >> /etc/resolv.conf
echo "options edns0 trust-ad" >> /etc/resolv.conf
echo "search ." >> /etc/resolv.conf

echo "DNS settings reset to default."
