# Variables that may be changed
VM_C_BOX = "generic/alpine311"
VM_C_MEMORY = "2048"
VM_C_CPUS = "2"

SERVER_NAME = "mlachhebS"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
    config.vm.box = VM_C_BOX
    config.vbguest.auto_update = false
    config.vm.provider "virtualbox" do |vb|
      vb.memory = VM_C_MEMORY
      vb.cpus = VM_C_CPUS
    end

  config.vm.define SERVER_NAME, primary: true do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.synced_folder ".", "/vagrant"
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.network "forwarded_port", guest: 80, host: 80
    server.vm.network "forwarded_port", guest: 6443, host: 6443
    server.vm.provision "shell", privileged: true, path: "scripts/install_server.sh", args: [SERVER_IP]
  end
end
