# Variables that may be changed
VM_C_BOX = "generic/alpine38"
VM_C_MEMORY = "1024"
VM_C_CPUS = "1"

SERVER_NAME = "mlachhebS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "mlachhebSW"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
    config.vm.box = VM_C_BOX
    config.vm.provider "virtualbox" do |vb|
      vb.memory = VM_C_MEMORY
      vb.cpus = VM_C_CPUS
    end

  config.vm.define SERVER_NAME, primary: true do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell", path: "install.sh"
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provision "shell", path: "install.sh"
  end
end